/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { AuthSessionFindManyArgs } from "../../authSession/base/AuthSessionFindManyArgs";
import { AuthSession } from "../../authSession/base/AuthSession";
import { AuthSessionWhereUniqueInput } from "../../authSession/base/AuthSessionWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: data,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        hashedPassword: true,
        id: true,
        lastName: true,
        passwordHash: true,
        roles: true,
        updatedAt: true,
        username: true,
        userName: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        hashedPassword: true,
        id: true,
        lastName: true,
        passwordHash: true,
        roles: true,
        updatedAt: true,
        username: true,
        userName: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        createdAt: true,
        email: true,
        firstName: true,
        hashedPassword: true,
        id: true,
        lastName: true,
        passwordHash: true,
        roles: true,
        updatedAt: true,
        username: true,
        userName: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          hashedPassword: true,
          id: true,
          lastName: true,
          passwordHash: true,
          roles: true,
          updatedAt: true,
          username: true,
          userName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          createdAt: true,
          email: true,
          firstName: true,
          hashedPassword: true,
          id: true,
          lastName: true,
          passwordHash: true,
          roles: true,
          updatedAt: true,
          username: true,
          userName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/authSessions")
  @ApiNestedQuery(AuthSessionFindManyArgs)
  async findAuthSessions(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AuthSession[]> {
    const query = plainToClass(AuthSessionFindManyArgs, request.query);
    const results = await this.service.findAuthSessions(params.id, {
      ...query,
      select: {
        associatedUser: true,
        authToken: true,
        createdAt: true,
        expiresAt: true,
        expiryDate: true,
        id: true,
        token: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        userReference: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/authSessions")
  async connectAuthSessions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuthSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      authSessions: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/authSessions")
  async updateAuthSessions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuthSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      authSessions: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/authSessions")
  async disconnectAuthSessions(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuthSessionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      authSessions: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
